# Generated by Django 4.2.17 on 2024-12-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('House', 'House'), ('Villa', 'Villa'), ('Flat', 'Flat')], default='House', max_length=20)),
                ('bedroom_count', models.PositiveIntegerField()),
                ('squarefootage', models.CharField(max_length=100)),
            ],
        ),
    ]
